name: Continuous Delivery

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    paths:
      - 'apps/**'
      - 'Dockerfile'
      - '.github/workflows/continuous-delivery.yml'
      - 'package.json'

jobs:
  PublishAcryss:
    name: Publish Acryss image to container registries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2.2.1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Acryss Docker image
        uses: docker/build-push-action@v3.2.0
        with:
          push: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
          context: .
          target: acryss-runner
          tags: ghcr.io/skyra-project/acryss:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  PublishNayre:
    name: Publish Nayre image to container registries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2.2.1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Nayre Docker image
        uses: docker/build-push-action@v3.2.0
        with:
          push: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
          context: .
          target: nayre-runner
          tags: ghcr.io/skyra-project/nayre:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  PublishFrontend:
    name: Publish Frontend image to container registries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2.2.1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Frontend Docker image
        uses: docker/build-push-action@v3.2.0
        with:
          push: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
          context: .
          target: frontend-runner
          tags: ghcr.io/skyra-project/nayre-web:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
