name: Continuous Delivery

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    paths:
      - 'apps/**'
      - 'Dockerfile'
      - '.github/workflows/continuous-delivery.yml'
      - 'package.json'

jobs:
  ExtractDockerTag:
    name: Extract Docker Tag
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.extract-tag.outputs.tag }}
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
      - name: Use Node.js v18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Install Dependencies
        run: yarn --immutable
      - name: Extract Docker Tag
        id: extract-tag
        uses: ./scripts/formatBranch
        with:
          branch: ${{ github.ref_name }}

  PublishAcryss:
    name: Publish Acryss image to container registries
    runs-on: ubuntu-latest
    needs: ExtractDockerTag
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2.2.1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Acryss Docker image
        uses: docker/build-push-action@v3.2.0
        with:
          outputs: ${{ github.event_name == 'push' && 'registry' || 'local' }}
          context: .
          target: acryss-runner
          tags: ghcr.io/skyra-project/acryss:${{ needs.ExtractDockerTag.outputs.tag }}

  PublishNayre:
    name: Publish Nayre image to container registries
    runs-on: ubuntu-latest
    needs: ExtractDockerTag
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2.2.1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Nayre Docker image
        uses: docker/build-push-action@v3.2.0
        with:
          outputs: ${{ github.event_name == 'push' && 'registry' || 'local' }}
          context: .
          target: nayre-runner
          tags: ghcr.io/skyra-project/nayre:${{ needs.ExtractDockerTag.outputs.tag }}

  PublishFrontend:
    name: Publish Frontend image to container registries
    runs-on: ubuntu-latest
    needs: ExtractDockerTag
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2.2.1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Frontend Docker image
        uses: docker/build-push-action@v3.2.0
        with:
          outputs: ${{ github.event_name == 'push' && 'registry' || 'local' }}
          context: .
          target: frontend-runner
          tags: ghcr.io/skyra-project/nayre-web:${{ needs.ExtractDockerTag.outputs.tag }}
