name: Continuous Delivery

on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths:
            - 'apps/**'
            - 'Dockerfile'
            - '.github/workflows/continuous-delivery.yml'
            - 'package.json'

jobs:
    PublishAcryss:
        name: Publish Acryss image to container registries
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Project
              uses: actions/checkout@v3
            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v2.2.1
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v2.1.0
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build and push Acryss Docker image
              uses: docker/build-push-action@v3.2.0
              with:
                  push: true
                  context: apps/acryss
                  tags: ghcr.io/skyra-project/acryss:latest

    PublishNayre:
        name: Publish Nayre image to container registries
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Project
              uses: actions/checkout@v3
            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v2.2.1
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v2.1.0
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build and push Nayre Docker image
              uses: docker/build-push-action@v3.2.0
              with:
                  push: true
                  context: apps/nayre
                  tags: ghcr.io/skyra-project/nayre:latest

    PublishFrontend:
        name: Publish Frontend image to container registries
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Project
              uses: actions/checkout@v3
            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v2.2.1
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v2.1.0
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build and push Frontend Docker image
              uses: docker/build-push-action@v3.2.0
              with:
                  push: true
                  context: apps/frontend
                  tags: ghcr.io/skyra-project/nayre-web:latest
